/*
Sonatype OSS Index

Testing VersionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ossindex

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	ossindex "github.com/sonatype-nexus-community/ossindex-api-client-go"
)

func Test_ossindex_VersionAPIService(t *testing.T) {

	configuration := ossindex.NewConfiguration()
	apiClient := ossindex.NewAPIClient(configuration)

	t.Run("Test VersionAPIService Get", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.VersionAPI.Get(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
